### ISSUE TITLE
Error when recalling previous answers

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#19]
I'm getting this error when I try to recall a previous answer using `[--prev|step.slide--]`

This might be because we don't have Next buttons which save previous answers yet. 

```
Fatal error: Uncaught Error: Call to a member function bindParam() on boolean in /var/www/html/app/model/slide.model.php:82 Stack trace: #0 /var/www/html/lib/functions.php(195): Slide->findPreviousAnswer('', '0', '1') #1 /var/www/html/app/view/project/slide.php(65): injectPrevAnswer('<h1>\nExplain ho...') #2 /var/www/html/lib/template.class.php(52): include('/var/www/html/a...') #3 /var/www/html/lib/controller.class.php(26): Template->render() #4 /var/www/html/lib/main.php(76): Controller->render() #5 /var/www/html/lib/main.php(112): init() #6 /var/www/html/public/index.php(11): require_once('/var/www/html/l...') #7 {main} thrown in /var/www/html/app/model/slide.model.php on line 82
```

**Comment by dantheta** [comment]
This should be fixed now.
