### ISSUE TITLE
Error when try to show previous answer from slide with multiple answers

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/alidade#25]
Is there a way we can recall a specific answer from a previous slide where that slide had multiple answers?

Error showing for that use-case right now with `[--prev|1.1--] `

```
Fatal error: Uncaught Error: Call to a member function bindParam() on boolean in /var/www/html/app/model/slide.model.php:82 Stack trace: #0 /var/www/html/lib/functions.php(197): Slide->findPreviousAnswer('', '1', '1') #1 /var/www/html/app/view/project/slide.php(65): injectPrevAnswer('<h2>\nExplain ho...') #2 /var/www/html/lib/template.class.php(52): include('/var/www/html/a...') #3 /var/www/html/lib/controller.class.php(26): Template->render() #4 /var/www/html/lib/main.php(76): Controller->render() #5 /var/www/html/lib/main.php(112): init() #6 /var/www/html/public/index.php(11): require_once('/var/www/html/l...') #7 {main} thrown in /var/www/html/app/model/slide.model.php on line 82
```

**Comment by edjw** [comment]
Actually this seems to be broken on recalling an answer from a slide with only one answer as well. This one feels like it might be a bug whereas the the multiple answers feature above may not be available?

Multiple errors showing

```
Array
(
    [0] => 23000
    [1] => 1048
    [2] => Column 'project' cannot be null
)
```

```
Fatal error: Uncaught Error: Call to a member function bindParam() on boolean in /var/www/html/app/model/slide.model.php:82 Stack trace: #0 /var/www/html/lib/functions.php(197): Slide->findPreviousAnswer('', '2', '3') #1 /var/www/html/app/view/project/slide.php(65): injectPrevAnswer('[--prev|2.3--]') #2 /var/www/html/lib/template.class.php(52): include('/var/www/html/a...') #3 /var/www/html/lib/controller.class.php(26): Template->render() #4 /var/www/html/lib/main.php(76): Controller->render() #5 /var/www/html/lib/main.php(112): init() #6 /var/www/html/public/index.php(11): require_once('/var/www/html/l...') #7 {main} thrown in /var/www/html/app/model/slide.model.php on line 82
```


I imagine the clue is in the project column can't be null and the first number parameter here being empty? `Slide->findPreviousAnswer('', '2', '3')`

**Comment by dantheta** [comment]
This can also be caused by an expired session.  I've rewritten quite a large part of this code, so could you re-test?
